version: '3.7'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"  
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: files
      MYSQL_USER: root
      MYSQL_PASSWORD: admin123
    volumes:
      - ./data:/var/lib/mysql  

  app:
    build: .
    container_name: node_app
    restart: always
    ports:
      - "3000:3000"  
    depends_on:
      - mysql  
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: admin123
      DB_DATABASE: files
    command: ["npm", "start"]
